use crate::config::project::ProjectConfig;
use crate::error::{Error, Result};
use indexmap::IndexMap;

/// A generated Helm chart as a map of relative file paths to contents.
pub struct HelmChart {
    /// Map of relative path (e.g., "Chart.yaml", "templates/deployment.yaml") to file content.
    pub files: IndexMap<String, String>,
}

/// Generate a complete Helm chart from a project config.
///
/// Returns a `HelmChart` containing all files needed for the chart:
/// - `Chart.yaml` metadata
/// - `values.yaml` generated from config
/// - `templates/` directory with all Go-template YAML files
pub fn generate(config: &ProjectConfig) -> Result<HelmChart> {
    let mut files = IndexMap::new();

    // Chart.yaml
    let chart_yaml = generate_chart_yaml(config);
    files.insert("Chart.yaml".to_string(), chart_yaml);

    // values.yaml
    let values = crate::helm::values::build(config)?;
    let values_yaml =
        serde_yaml::to_string(&values).map_err(|e| Error::HelmGeneration(e.to_string()))?;
    files.insert("values.yaml".to_string(), values_yaml);

    // templates/
    for (name, content) in crate::helm::templates::all_templates() {
        files.insert(format!("templates/{name}"), content.to_string());
    }

    Ok(HelmChart { files })
}

fn generate_chart_yaml(config: &ProjectConfig) -> String {
    let name = &config.project.name;
    let description = config
        .project
        .description
        .as_deref()
        .unwrap_or("Generated by cc-container");

    format!(
        "apiVersion: v2\n\
         name: {name}\n\
         description: {description}\n\
         type: application\n\
         version: 0.1.0\n\
         appVersion: \"1.0\"\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::project::*;
    use indexmap::IndexMap;

    fn minimal_config() -> ProjectConfig {
        ProjectConfig {
            project: ProjectMeta {
                name: "test-chart".to_string(),
                description: Some("A test chart".to_string()),
            },
            agent: AgentConfig {
                agent_type: AgentType::Claude,
                claude_version: "latest".to_string(),
                codex_version: "latest".to_string(),
            },
            image: ImageConfig::default(),
            modules: IndexMap::new(),
            auth: AuthConfig::default(),
            firewall: FirewallConfig::default(),
            workspace: WorkspaceConfig::default(),
            volumes: IndexMap::new(),
            environment: EnvironmentConfig::default(),
            services: IndexMap::new(),
            mcp: IndexMap::new(),
            runtime: RuntimeConfig::default(),
            helm: HelmConfig::default(),
        }
    }

    #[test]
    fn chart_yaml_contains_name() {
        let config = minimal_config();
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("name: test-chart"));
    }

    #[test]
    fn chart_yaml_contains_description() {
        let config = minimal_config();
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("description: A test chart"));
    }

    #[test]
    fn chart_yaml_uses_default_description_when_none() {
        let mut config = minimal_config();
        config.project.description = None;
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("description: Generated by cc-container"));
    }

    #[test]
    fn chart_yaml_has_api_version() {
        let config = minimal_config();
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("apiVersion: v2"));
    }

    #[test]
    fn chart_yaml_has_version_fields() {
        let config = minimal_config();
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("version: 0.1.0"));
        assert!(yaml.contains("appVersion: \"1.0\""));
    }

    #[test]
    fn chart_yaml_type_is_application() {
        let config = minimal_config();
        let yaml = generate_chart_yaml(&config);
        assert!(yaml.contains("type: application"));
    }
}
