apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.secrets.authKeys }}
  # {{ .description }}
  {{ .key }}: "REPLACE_ME"
  {{- end }}
  {{- range $key, $val := .Values.secrets.serviceCredentials }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
